# Внутренние сертификаты (bitwarden-sdk, webhooks и т.д.). Публичные — позже через ACME.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selfSigned: {}
