# remoteRef.key — имя секрета в BSM или UUID секрета.
# Если key — НЕ UUID, по доке ESO обязателен remoteRef.property = projectID (тот же, что в SecretStore).
# https://external-secrets.io/latest/provider/bitwarden-secrets-manager/
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-tzone
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-tzone
    kind: SecretStore
  target:
    name: tzone-sm-secrets
    creationPolicy: Owner
  data:
    - secretKey: example
      remoteRef:
        key: change-me
        property: b8e06e87-b3e1-4f5b-890b-b46c00ee6a18
