apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-llm-orchestrator.yaml
  - certificate-llms-chilik-net.yaml
  - llm-orchestrator-web.yaml
  - ingress-llms-chilik-net.yaml
