server {
  listen          80;
  server_name     api.chilik.net learn-english.chilik.net;
  
  # Для веб-рута certbot (Let's Encrypt валидация)
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }
  
  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen       443 ssl;
  server_name  api.chilik.net;

  resolver 127.0.0.11 valid=10s;

  ssl_certificate     /etc/nginx/ssl/api.chilik.net.crt;
  ssl_certificate_key /etc/nginx/ssl/api.chilik.net.key;
  ssl_trusted_certificate /etc/nginx/ssl/api.chilik.net.bundle.crt;

  client_max_body_size 100M;

  location / {
    set $backend "backend:8080";
    proxy_pass http://$backend;

    proxy_request_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen 443 ssl;
  server_name     learn-english.chilik.net;

  resolver 127.0.0.11 valid=10s;

  ssl_certificate     /etc/nginx/ssl/api.chilik.net.crt;
  ssl_certificate_key /etc/nginx/ssl/api.chilik.net.key;
  ssl_trusted_certificate /etc/nginx/ssl/api.chilik.net.bundle.crt;

  client_max_body_size 100M;

  location / {
    set $backend "web:80";
    proxy_pass http://$backend;

    proxy_request_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
